# Atelier Numpy

## Partie 1 : Listes Python vs tableaux NumPy

### 1 . Créer une liste Python stockant ces températures (24.5, 25.1, 26.3, 27.0 et 25.8)

In [ ]:
# Création d'une liste Python 
temperatures_liste = [24.5, 25.1, 26.3, 27.0, 25.8]

print("Liste Python :", temperatures_liste)

Liste Python : [24.5, 25.1, 26.3, 27.0, 25.8]


### 2 . Créer un tableau NumPy équivalent stockant ces températures

In [1]:
import numpy as np

# Conversion de la liste en tableau NumPy 
temperatures_numpy = np.array([24.5, 25.1, 26.3, 27.0, 25.8])

print("Tableau NumPy :", temperatures_numpy)

Tableau NumPy : [24.5 25.1 26.3 27.  25.8]


### 3 . Effectuer une multiplication par 2 sur ces deux collections

In [3]:
# Multiplication par 2 de la liste Python
temperatures_liste = [24.5, 25.1, 26.3, 27.0, 25.8]
liste_multipliee = temperatures_liste * 2

# Multiplication par 2 du tableau NumPy
temperatures_numpy = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
numpy_multiplie = temperatures_numpy * 2

# Affichage des deux résultats
print("Résultat liste Python :", liste_multipliee)
print("Résultat tableau NumPy :", numpy_multiplie)

Résultat liste Python : [24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
Résultat tableau NumPy : [49.  50.2 52.6 54.  51.6]


### 4 . Quelle différence observe-t-on ?

Différence : La liste Python a été dupliquée (répétition des éléments),alors que le tableau NumPy a subi une multiplication vectorielle de chaque élément.

## Partie 2 : Création des données

### 1 . Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro


In [4]:
# Initialisation d'un tableau de 10 zéros (floats par défaut)
import numpy as np
capteurs_zeros = np.zeros(10)

# Affichage du tableau
print("Capteurs à zéro :", capteurs_zeros)

Capteurs à zéro : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 2 . Créer un tableau contenant 10 valeurs égales à 1


In [8]:
import numpy as np
# Initialisation d'un tableau de 10 uns
capteurs_uns = np.ones(10)

print("Capteurs à un :", capteurs_uns)

Capteurs à un : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 3 . Créer un tableau de 10 valeurs initialisées à 25

In [10]:
import numpy as np
# Initialisation d'un tableau de 10 éléments contenant chacun la valeur 25
capteurs_25 = np.full(10, 25.0)
print("Capteurs à 25 :", capteurs_25)

Capteurs à 25 : [25. 25. 25. 25. 25. 25. 25. 25. 25. 25.]


### 4 . Créer une matrice identité de taille 5 × 5

In [11]:
# Création d'une matrice identité 5x5
import numpy as np
matrice_identite = np.eye(5)
print("Matrice identité 5x5 :\n", matrice_identite)

Matrice identité 5x5 :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


###  5 . Créer les 24 heures (de 0 à 23) de mesure d’une journée

In [12]:
# Génération d'un tableau allant de 0 à 23 inclus 
import numpy as np
heures_journee = np.arange(0, 24)

print("Heures de la journée :", heures_journee)

Heures de la journée : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### 6 . Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C

In [13]:
import numpy as np
temperatures_linspace = np.linspace(20, 30, 10)
print("Températures réparties :", temperatures_linspace)

Températures réparties : [20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


### 7 . Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles

In [15]:
import numpy as np
np.random.seed(42)

# Génération de 100 températures aléatoires uniformes entre 15 °C et 35 °C
mesures_aleatoires = np.random.uniform(15, 35, 100)

print("10 premières mesures de température aléatoires :\n", mesures_aleatoires[:10])

10 premières mesures de température aléatoires :
 [22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041
 16.16167224 32.32352292 27.02230023 29.16145156]


## Partie 3 : Exploration des tableaux

### 1 . Créer aléatoirement un tableau représentant les 24 températures d'une journée

In [ ]:
import numpy as np
# Fixation de la seed pour la reproductibilité locale
np.random.seed(10)

# Génération de 24 températures aléatoires entre 18 °C et 30 °C
temperatures_24h = np.random.uniform(18, 30, 24)

print("Températures des 24 heures :\n", temperatures_24h)

Températures des 24 heures :
 [34.96905415 18.45654289 31.94026117 34.47368542 28.96715427 22.9455262
 22.35738302 34.73167567 21.7204384  19.94347591 33.077916   38.97465362
 18.08686186 29.26822979 35.87766116 31.47557347 33.87861698 24.4212735
 38.1910307  33.72066723 29.9359761  21.12774105 26.21349672 32.83093953]
