# Atelier NumPy

## Partie 1 : Listes Python vs tableaux NumPy

### 1 . Créer une liste Python stockant ces températures (24.5, 25.1, 26.3, 27.0 et 25.8)

In [9]:
# Création d'une liste Python 
temperatures = [24.5, 25.1, 26.3, 27.0, 25.8]

# Affichage de la liste pour vérification
print("Liste Python :", temperatures)

Liste Python : [24.5, 25.1, 26.3, 27.0, 25.8]


### 2 .Créer un tableau NumPy équivalent stockant ces températures

In [2]:
import numpy as np

# Conversion de la liste en tableau NumPy (ndarray)
temperatures_numpy = np.array([24.5, 25.1, 26.3, 27.0, 25.8])

# Affichage du tableau NumPy
print("Tableau NumPy :", temperatures_numpy)

Tableau NumPy : [24.5 25.1 26.3 27.  25.8]


### 3 . Effectuer une multiplication par 2 sur ces deux collections

In [5]:
# Multiplication par 2 de la liste Python
temperatures = [24.5, 25.1, 26.3, 27.0, 25.8]
liste_multipliee = temperatures * 2

# Multiplication par 2 du tableau NumPy
numpy_multiplie = temperatures_numpy * 2

# Affichage des deux résultats
print("Résultat liste Python :", liste_multipliee)
print("Résultat tableau NumPy :", numpy_multiplie)

Résultat liste Python : [24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
Résultat tableau NumPy : [49.  50.2 52.6 54.  51.6]


### 4 . Quelle différence observe-t-on ?

Différence : La liste Python a été dupliquée (répétition des éléments),alors que le tableau NumPy a subi une multiplication vectorielle de chaque élément.

## Partie 2 : Création des données

### 1 . Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro

In [3]:
# Initialisation d'un tableau de 10 zéros (floats par défaut)
import numpy as np
capteurs_zeros = np.zeros(10)

# Affichage du tableau
print("Capteurs à zéro :", capteurs_zeros)

Capteurs à zéro : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 2 . Créer un tableau contenant 10 valeurs égales à 1

In [2]:
import numpy as np
# Initialisation d'un tableau de 10 uns
capteurs_uns = np.ones(10)

print("Capteurs à un :", capteurs_uns)

Capteurs à un : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 3 . Créer un tableau de 10 valeurs initialisées à 25


In [4]:
import numpy as np
# Initialisation d'un tableau de 10 éléments contenant chacun la valeur 25
capteurs_25 = np.full(10, 25.0)
print("Capteurs à 25 :", capteurs_25)

Capteurs à 25 : [25. 25. 25. 25. 25. 25. 25. 25. 25. 25.]


### 4 . Créer une matrice identité de taille 5 × 5

In [5]:
# Création d'une matrice identité 5x5
import numpy as np
matrice_identite = np.eye(5)
print("Matrice identité 5x5 :\n", matrice_identite)

Matrice identité 5x5 :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


###  5 . Créer les 24 heures (de 0 à 23) de mesure d’une journée

In [6]:
# Génération d'un tableau allant de 0 à 23 inclus 
import numpy as np
heures_journee = np.arange(0, 24)

print("Heures de la journée :", heures_journee)

Heures de la journée : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### 6 . Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C

In [7]:
import numpy as np
temperatures_linspace = np.linspace(20, 30, 10)
print("Températures réparties :", temperatures_linspace)

Températures réparties : [20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


### 7 . Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles

In [8]:
import numpy as np
np.random.seed(42)

# Génération de 100 températures aléatoires uniformes entre 15 °C et 35 °C
mesures_aleatoires = np.random.uniform(15, 35, 100)

print("10 premières mesures de température aléatoires :\n", mesures_aleatoires[:10])

10 premières mesures de température aléatoires :
 [22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041
 16.16167224 32.32352292 27.02230023 29.16145156]


## Partie 3 : Exploration des tableaux

### 1 . Créer aléatoirement un tableau représentant les 24 températures d'une journée

In [9]:
import numpy as np
# Fixation de la seed pour la reproductibilité locale
np.random.seed(10)

# Génération de 24 températures aléatoires entre 18 °C et 30 °C
temperatures_24h = np.random.uniform(18, 30, 24)

print("Températures des 24 heures :\n", temperatures_24h)

Températures des 24 heures :
 [27.25584772 18.24902339 25.60377882 26.98564659 23.98208415 20.69755975
 20.37675438 27.12636855 20.02933004 19.06007777 26.22431782 29.44072015
 18.0473792  24.14630716 27.75145154 25.3503128  26.66106381 21.50251282
 29.01328947 26.5749094  24.51053242 19.70604057 22.48008912 26.08960338]


### 2 . Déterminer les propriétés suivantes du tableau :   a) nombre de dimensions ; b) nombre de valeurs ; c) type des données ; d) forme du tableau

In [10]:
# Récupération des attributs du tableau
import numpy as np  
dims = temperatures_24h.ndim
nb_valeurs = temperatures_24h.size
type_data = temperatures_24h.dtype
forme = temperatures_24h.shape

# Affichage structuré des propriétés
print(f"a) Nombre de dimensions : {dims}")
print(f"b) Nombre de valeurs    : {nb_valeurs}")
print(f"c) Type des données     : {type_data}")
print(f"d) Forme du tableau     : {forme}")

a) Nombre de dimensions : 1
b) Nombre de valeurs    : 24
c) Type des données     : float64
d) Forme du tableau     : (24,)


## Partie 4 : Indexation et slicing

### 1 . la première mesure

In [11]:
# Accès à la première valeur du tableau
import numpy as np
np.random.seed(10)
temperatures_24h = np.random.uniform(18, 30, 24)
premiere_mesure = temperatures_24h[0]

print("Première mesure  :", premiere_mesure)

Première mesure  : 27.25584771920095


### 2 . la dernière mesure

In [12]:
import numpy as np
np.random.seed(10)
temperatures_24h = np.random.uniform(18, 30, 24)
# Accès à la dernière valeur du tableau
derniere_mesure = temperatures_24h[-1]

print("Dernière mesure  :", derniere_mesure)

Dernière mesure  : 26.08960338079614


### 3 . la température de 8h

In [13]:
import numpy as np
np.random.seed(10)
temperatures_24h = np.random.uniform(18, 30, 24)    
# Accès direct à l'index 8
temp_8h = temperatures_24h[8]

print("Température à 8h :", temp_8h)

Température à 8h : 20.029330038750427


### 4 . les températures de 8h à 12h

In [14]:
import numpy as np
np.random.seed(10)
temperatures_24h = np.random.uniform(18, 30, 24)
# Slicing de l'index 8 à l'index 12 inclus (13 exclu)
temp_8h_12h = temperatures_24h[8:13]

print("Températures de 8h à 12h :\n", temp_8h_12h)

Températures de 8h à 12h :
 [20.02933004 19.06007777 26.22431782 29.44072015 18.0473792 ]


### 5 . les températures des 6 premières heures

In [15]:
import numpy as np
np.random.seed(10)
temperatures_24h = np.random.uniform(18, 30, 24)
# Slicing des 6 premières valeurs
six_premieres_heures = temperatures_24h[:6]

print("Températures des 6 premières heures :\n", six_premieres_heures)

Températures des 6 premières heures :
 [27.25584772 18.24902339 25.60377882 26.98564659 23.98208415 20.69755975]


### 6 . les températures des heures paires

In [16]:
import numpy as np
np.random.seed(10)
temperatures_24h = np.random.uniform(18, 30, 24)
# Slicing de l'ensemble du tableau avec un pas de 2
temp_heures_paires = temperatures_24h[::2]

print("Températures aux heures paires :\n", temp_heures_paires)

Températures aux heures paires :
 [27.25584772 25.60377882 23.98208415 20.37675438 20.02933004 26.22431782
 18.0473792  27.75145154 26.66106381 29.01328947 24.51053242 22.48008912]


## Partie 5 : Filtrage booléen

### 1. Afficher les températures supérieures à 30 °C

In [17]:
import numpy as np
np.random.seed(42)
temperatures_larges = np.random.uniform(15, 40, 24)

# Étape 1 : Créer la condition logique, Étape 2 : L'appliquer en indexation
temperatures_chaudes = temperatures_larges[temperatures_larges > 30]

print("Mesures de température larges :\n", temperatures_larges)
print("Températures supérieures à 30 °C :", temperatures_chaudes)

Mesures de température larges :
 [24.36350297 38.76785766 33.29984855 29.9664621  18.90046601 18.89986301
 16.4520903  36.65440364 30.02787529 32.70181444 15.51461236 39.2477463
 35.81106602 20.30847777 19.54562418 19.58511275 22.60605607 28.11891079
 25.79862547 22.2807285  30.29632237 18.48734652 22.30361621 24.15904608]
Températures supérieures à 30 °C : [38.76785766 33.29984855 36.65440364 30.02787529 32.70181444 39.2477463
 35.81106602 30.29632237]


### 2 . Afficher les températures « normales » càd comprises entre 20 °C et 30 °C

In [18]:
import numpy as np
np.random.seed(10)
temperatures_larges = np.random.uniform(15, 40, 24)
# Combinaison des filtres >= 20 et <= 30
temperatures_normales = temperatures_larges[(temperatures_larges >= 20) & (temperatures_larges <= 30)]

print("Températures normales (20 à 30 °C inclus) :\n", temperatures_normales)

Températures normales (20 à 30 °C inclus) :
 [27.46267531 20.61991614 27.80480658 22.2969017  28.5636092  24.333519  ]


### 3 . Supposons qu'une température supérieure à 35 °C soit considérée comme anormale. Déterminer anomalies, un tableau de booléen précisant les anomalies

In [19]:
import numpy as np
np.random.seed(10)
temperatures_larges = np.random.uniform(15, 40, 24)
# Génération du masque de booléens pour les valeurs strictement supérieures à 35
anomalies = temperatures_larges > 35

print("Masque logique d'anomalies (>35 °C) :\n", anomalies)

Masque logique d'anomalies (>35 °C) :
 [False False False False False False False False False False False  True
 False False  True False False False  True False False False False False]


### 4 . Déterminer le nombre de températures anormales à l’aide de la variable anomalies

In [20]:
import numpy as np
np.random.seed(10)
temperatures_larges = np.random.uniform(15, 40, 24)
# Génération du masque de booléens pour les valeurs strictement supérieures à 35
anomalies = temperatures_larges > 35
# Somme du tableau de booléens pour compter les True
nombre_anomalies = np.sum(anomalies)

print("Nombre total de températures anormales :", nombre_anomalies)

Nombre total de températures anormales : 3


## Partie 6 : Manipulation des dimensions

### 1 . Créer aléatoirement la matrice représentant les températures mesurées par ces capteurs durant une journée

In [21]:
import numpy as np
np.random.seed(15)

# Création d'une matrice (5, 24) représentant 5 capteurs et 24 heures de mesure
matrice_temperatures = np.random.uniform(15, 30, (5, 24))

print("Forme (shape) de la matrice :", matrice_temperatures.shape)
print("Nombre de dimensions (ndim) :", matrice_temperatures.ndim)

Forme (shape) de la matrice : (5, 24)
Nombre de dimensions (ndim) : 2


### 2 . Transformer la matrice en un tableau unidimensionnel

In [22]:
import numpy as np
np.random.seed(15)
# Création d'une matrice (5, 24) représentant 5 capteurs et 24 heures de mesure
matrice_temperatures = np.random.uniform(15, 30, (5, 24))
#  Aplatissement de la matrice
tableau_plat = matrice_temperatures.flatten()

print("Nouvelle forme du tableau aplati :", tableau_plat.shape)
print("Nombre de dimensions du tableau aplati :", tableau_plat.ndim)

Nouvelle forme du tableau aplati : (120,)
Nombre de dimensions du tableau aplati : 1


### 3 . Déterminer la transposée de la matrice

In [24]:
import numpy as np
# Calcul de la transposée
matrice_transposee = matrice_temperatures.T

print("Forme originale :", matrice_temperatures.shape)
print("Forme de la transposée :", matrice_transposee.shape)

Forme originale : (5, 24)
Forme de la transposée : (24, 5)


### 4 . Extraire toutes les mesures du capteur 1

In [25]:
# Extraction de la ligne d'index 0
mesures_capteur_1 = matrice_temperatures[0, :]

print("Mesures du capteur 1 (24 valeurs) :\n", mesures_capteur_1)

Mesures du capteur 1 (24 valeurs) :
 [27.73226546 17.68343887 15.81544821 20.42307669 19.13101393 22.95000337
 19.58878374 19.56711539 16.67611914 18.74848521 28.76444847 18.9622028
 25.76660531 27.98572551 27.10619223 18.15825874 17.50864547 15.70059588
 15.59133468 18.00346215 29.97815104 20.59180467 26.40765411 22.10211664]


### 5 . Extraire toutes les mesures du capteur 5

In [26]:
# Extraction de la ligne d'index 4
mesures_capteur_5 = matrice_temperatures[4, :]

print("Mesures du capteur 5 (24 valeurs) :\n", mesures_capteur_5)

Mesures du capteur 5 (24 valeurs) :
 [18.01079949 21.31767089 28.98416015 20.44936197 15.22506235 28.49591113
 24.2310025  29.56413102 24.32430501 29.04393684 23.98559507 17.08918073
 25.17562085 23.19508571 15.13566575 26.6215536  16.82136757 22.76091214
 24.98628516 26.44369262 29.11318321 16.85981347 18.14993607 20.48051553]


### 6 . Extraire les mesures de tous les capteurs à 10h

In [27]:
# Extraction de la colonne d'index 10 pour toutes les lignes
mesures_10h = matrice_temperatures[:, 10]

print("Mesures de tous les capteurs à 10h :", mesures_10h)

Mesures de tous les capteurs à 10h : [28.76444847 24.34527929 19.03242452 19.42944858 23.98559507]


###  7 . Extraire les mesures des capteurs 2 à 4 entre 8h et 12h.


In [28]:
# Extraction de la sous-matrice combinant les sélections de lignes et colonnes
sous_matrice = matrice_temperatures[1:4, 8:13]

print("Sous-matrice capteurs 2-4 de 8h à 12h :\n", sous_matrice)

Sous-matrice capteurs 2-4 de 8h à 12h :
 [[24.98441307 20.46493201 24.34527929 24.64087328 21.2997273 ]
 [26.87699252 21.65811884 19.03242452 15.35856633 20.56998849]
 [16.91388232 19.5548061  19.42944858 23.53657556 26.15129444]]


## Partie 7 : Concaténation

### 1 . Créer aléatoirement la matrice représentant les températures mesurées par les 3 capteurs durant une journée

In [29]:
np.random.seed(25)

# Création de la matrice pour le bâtiment 2 de dimension (3, 24)
matrice_batiment_2 = np.random.uniform(15, 30, (3, 24))

print("Forme de la matrice bâtiment 2 :", matrice_batiment_2.shape)

Forme de la matrice bâtiment 2 : (3, 24)


### 2 . Déterminer de deux manières différentes la matrice qui fusionne les températures mesurées par les 8 capteurs durant une journée

In [30]:
# Méthode 1 : Concaténation le long de l'axe 0
fusion_methode_1 = np.concatenate((matrice_temperatures, matrice_batiment_2), axis=0)

# Méthode 2 : Empilement vertical
fusion_methode_2 = np.vstack((matrice_temperatures, matrice_batiment_2))

print("Forme finale fusionnée (Méthode 1) :", fusion_methode_1.shape)
print("Forme finale fusionnée (Méthode 2) :", fusion_methode_2.shape)

Forme finale fusionnée (Méthode 1) : (8, 24)
Forme finale fusionnée (Méthode 2) : (8, 24)


## Partie 8 : Calcul scientifique

### 1 . Pour les températures calculer le minimum, le maximum, la somme, la moyenne, la médiane, la variance et l’écart-type

In [31]:
# Calculs statistiques élémentaires
val_min = np.min(temperatures_24h)
val_max = np.max(temperatures_24h)
somme = np.sum(temperatures_24h)
moyenne = np.mean(temperatures_24h)
mediane = np.median(temperatures_24h)
variance = np.var(temperatures_24h)
ecart_type = np.std(temperatures_24h)

# Affichage formaté des résultats
print(f"Minimum    : {val_min:.2f} °C")
print(f"Maximum    : {val_max:.2f} °C")
print(f"Somme      : {somme:.2f} °C")
print(f"Moyenne    : {moyenne:.2f} °C")
print(f"Médiane    : {mediane:.2f} °C")
print(f"Variance   : {variance:.4f}")
print(f"Écart-type : {ecart_type:.4f} °C")

Minimum    : 18.05 °C
Maximum    : 29.44 °C
Somme      : 576.87 °C
Moyenne    : 24.04 °C
Médiane    : 24.93 °C
Variance   : 11.8944
Écart-type : 3.4488 °C


### 2 : Standardiser le tableau des températures puis vérifier les valeurs de la moyenne et de l’écart-type du tableau standardisé

In [32]:
# Application de la formule de standardisation
temp_standardisee = (temperatures_24h - moyenne) / ecart_type

# Vérification de la moyenne et de l'écart-type
moyenne_std = np.mean(temp_standardisee)
ecart_type_std = np.std(temp_standardisee)

print(f"Moyenne après standardisation  : {moyenne_std:.2e} (très proche de 0)")
print(f"Écart-type après standardisation : {ecart_type_std:.2f} (égal à 1.0)")

Moyenne après standardisation  : -8.88e-16 (très proche de 0)
Écart-type après standardisation : 1.00 (égal à 1.0)
