# Atelier Numpy

## Partie 1 : Listes Python vs tableaux NumPy

### 1 . Créer une liste Python stockant ces températures (24.5, 25.1, 26.3, 27.0 et 25.8)

In [ ]:
# Création d'une liste Python 
temperatures_liste = [24.5, 25.1, 26.3, 27.0, 25.8]

print("Liste Python :", temperatures_liste)

Liste Python : [24.5, 25.1, 26.3, 27.0, 25.8]


### 2 . Créer un tableau NumPy équivalent stockant ces températures

In [1]:
import numpy as np

# Conversion de la liste en tableau NumPy 
temperatures_numpy = np.array([24.5, 25.1, 26.3, 27.0, 25.8])

print("Tableau NumPy :", temperatures_numpy)

Tableau NumPy : [24.5 25.1 26.3 27.  25.8]


### 3 . Effectuer une multiplication par 2 sur ces deux collections

In [3]:
# Multiplication par 2 de la liste Python
temperatures_liste = [24.5, 25.1, 26.3, 27.0, 25.8]
liste_multipliee = temperatures_liste * 2

# Multiplication par 2 du tableau NumPy
temperatures_numpy = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
numpy_multiplie = temperatures_numpy * 2

# Affichage des deux résultats
print("Résultat liste Python :", liste_multipliee)
print("Résultat tableau NumPy :", numpy_multiplie)

Résultat liste Python : [24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
Résultat tableau NumPy : [49.  50.2 52.6 54.  51.6]


### 4 . Quelle différence observe-t-on ?

Différence : La liste Python a été dupliquée (répétition des éléments),alors que le tableau NumPy a subi une multiplication vectorielle de chaque élément.

## Partie 2 : Création des données

### 1 . Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro


In [4]:
# Initialisation d'un tableau de 10 zéros (floats par défaut)
import numpy as np
capteurs_zeros = np.zeros(10)

# Affichage du tableau
print("Capteurs à zéro :", capteurs_zeros)

Capteurs à zéro : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 2 . Créer un tableau contenant 10 valeurs égales à 1


In [8]:
import numpy as np
# Initialisation d'un tableau de 10 uns
capteurs_uns = np.ones(10)

print("Capteurs à un :", capteurs_uns)

Capteurs à un : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 3 . Créer un tableau de 10 valeurs initialisées à 25

In [10]:
import numpy as np
# Initialisation d'un tableau de 10 éléments contenant chacun la valeur 25
capteurs_25 = np.full(10, 25.0)
print("Capteurs à 25 :", capteurs_25)

Capteurs à 25 : [25. 25. 25. 25. 25. 25. 25. 25. 25. 25.]


### 4 . Créer une matrice identité de taille 5 × 5

In [11]:
# Création d'une matrice identité 5x5
import numpy as np
matrice_identite = np.eye(5)
print("Matrice identité 5x5 :\n", matrice_identite)

Matrice identité 5x5 :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


###  5 . Créer les 24 heures (de 0 à 23) de mesure d’une journée

In [12]:
# Génération d'un tableau allant de 0 à 23 inclus 
import numpy as np
heures_journee = np.arange(0, 24)

print("Heures de la journée :", heures_journee)

Heures de la journée : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### 6 . Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C

In [13]:
import numpy as np
temperatures_linspace = np.linspace(20, 30, 10)
print("Températures réparties :", temperatures_linspace)

Températures réparties : [20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


### 7 . Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles

In [15]:
import numpy as np
np.random.seed(42)

# Génération de 100 températures aléatoires uniformes entre 15 °C et 35 °C
mesures_aleatoires = np.random.uniform(15, 35, 100)

print("10 premières mesures de température aléatoires :\n", mesures_aleatoires[:10])

10 premières mesures de température aléatoires :
 [22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041
 16.16167224 32.32352292 27.02230023 29.16145156]


## Partie 3 : Exploration des tableaux

### 1 . Créer aléatoirement un tableau représentant les 24 températures d'une journée

In [18]:
import numpy as np
# Fixation de la seed pour la reproductibilité locale
np.random.seed(10)

# Génération de 24 températures aléatoires entre 18 °C et 30 °C
temperatures_24h = np.random.uniform(18, 30, 24)

print("Températures des 24 heures :\n", temperatures_24h)

Températures des 24 heures :
 [27.25584772 18.24902339 25.60377882 26.98564659 23.98208415 20.69755975
 20.37675438 27.12636855 20.02933004 19.06007777 26.22431782 29.44072015
 18.0473792  24.14630716 27.75145154 25.3503128  26.66106381 21.50251282
 29.01328947 26.5749094  24.51053242 19.70604057 22.48008912 26.08960338]


### 2 . Déterminer les propriétés suivantes du tableau :   a) nombre de dimensions ; b) nombre de valeurs ; c) type des données ; d) forme du tableau

In [19]:
# Récupération des attributs du tableau
import numpy as np  
dims = temperatures_24h.ndim
nb_valeurs = temperatures_24h.size
type_data = temperatures_24h.dtype
forme = temperatures_24h.shape

# Affichage structuré des propriétés
print(f"a) Nombre de dimensions : {dims}")
print(f"b) Nombre de valeurs    : {nb_valeurs}")
print(f"c) Type des données     : {type_data}")
print(f"d) Forme du tableau     : {forme}")

a) Nombre de dimensions : 1
b) Nombre de valeurs    : 24
c) Type des données     : float64
d) Forme du tableau     : (24,)


## Partie 4 : Indexation et slicing

### 1 . la première mesure

In [22]:
# Accès à la première valeur du tableau
import numpy as np
np.random.seed(10)
temperatures_24h = np.random.uniform(18, 30, 24)
premiere_mesure = temperatures_24h[0]

print("Première mesure  :", premiere_mesure)

Première mesure  : 27.25584771920095


### 2 . la dernière mesure

In [23]:
import numpy as np
np.random.seed(10)
temperatures_24h = np.random.uniform(18, 30, 24)
# Accès à la dernière valeur du tableau
derniere_mesure = temperatures_24h[-1]

print("Dernière mesure  :", derniere_mesure)

Dernière mesure  : 26.08960338079614


### 3 . la température de 8h

In [24]:
import numpy as np
np.random.seed(10)
temperatures_24h = np.random.uniform(18, 30, 24)    
# Accès direct à l'index 8
temp_8h = temperatures_24h[8]

print("Température à 8h :", temp_8h)

Température à 8h : 20.029330038750427


### 4 . les températures de 8h à 12h

In [25]:
import numpy as np
np.random.seed(10)
temperatures_24h = np.random.uniform(18, 30, 24)
# Slicing de l'index 8 à l'index 12 inclus (13 exclu)
temp_8h_12h = temperatures_24h[8:13]

print("Températures de 8h à 12h :\n", temp_8h_12h)

Températures de 8h à 12h :
 [20.02933004 19.06007777 26.22431782 29.44072015 18.0473792 ]


### 5 . les températures des 6 premières heures

In [26]:
import numpy as np
np.random.seed(10)
temperatures_24h = np.random.uniform(18, 30, 24)
# Slicing des 6 premières valeurs
six_premieres_heures = temperatures_24h[:6]

print("Températures des 6 premières heures :\n", six_premieres_heures)

Températures des 6 premières heures :
 [27.25584772 18.24902339 25.60377882 26.98564659 23.98208415 20.69755975]


### 6 . les températures des heures paires

In [27]:
import numpy as np
np.random.seed(10)
temperatures_24h = np.random.uniform(18, 30, 24)
# Slicing de l'ensemble du tableau avec un pas de 2
temp_heures_paires = temperatures_24h[::2]

print("Températures aux heures paires :\n", temp_heures_paires)

Températures aux heures paires :
 [27.25584772 25.60377882 23.98208415 20.37675438 20.02933004 26.22431782
 18.0473792  27.75145154 26.66106381 29.01328947 24.51053242 22.48008912]


## Partie 5 : Filtrage booléen

### 1. Afficher les températures supérieures à 30 °C

In [28]:
import numpy as np
np.random.seed(42)
temperatures_larges = np.random.uniform(15, 40, 24)

# Étape 1 : Créer la condition logique, Étape 2 : L'appliquer en indexation
temperatures_chaudes = temperatures_larges[temperatures_larges > 30]

print("Mesures de température larges :\n", temperatures_larges)
print("Températures supérieures à 30 °C :", temperatures_chaudes)

Mesures de température larges :
 [24.36350297 38.76785766 33.29984855 29.9664621  18.90046601 18.89986301
 16.4520903  36.65440364 30.02787529 32.70181444 15.51461236 39.2477463
 35.81106602 20.30847777 19.54562418 19.58511275 22.60605607 28.11891079
 25.79862547 22.2807285  30.29632237 18.48734652 22.30361621 24.15904608]
Températures supérieures à 30 °C : [38.76785766 33.29984855 36.65440364 30.02787529 32.70181444 39.2477463
 35.81106602 30.29632237]


### 2 . Afficher les températures « normales » càd comprises entre 20 °C et 30 °C

In [29]:
import numpy as np
np.random.seed(10)
temperatures_larges = np.random.uniform(15, 40, 24)
# Combinaison des filtres >= 20 et <= 30
temperatures_normales = temperatures_larges[(temperatures_larges >= 20) & (temperatures_larges <= 30)]

print("Températures normales (20 à 30 °C inclus) :\n", temperatures_normales)

Températures normales (20 à 30 °C inclus) :
 [27.46267531 20.61991614 27.80480658 22.2969017  28.5636092  24.333519  ]


### 3 . Supposons qu'une température supérieure à 35 °C soit considérée comme anormale. Déterminer anomalies, un tableau de booléen précisant les anomalies

In [30]:
import numpy as np
np.random.seed(10)
temperatures_larges = np.random.uniform(15, 40, 24)
# Génération du masque de booléens pour les valeurs strictement supérieures à 35
anomalies = temperatures_larges > 35

print("Masque logique d'anomalies (>35 °C) :\n", anomalies)

Masque logique d'anomalies (>35 °C) :
 [False False False False False False False False False False False  True
 False False  True False False False  True False False False False False]


### 4 . Déterminer le nombre de températures anormales à l’aide de la variable anomalies

In [31]:
import numpy as np
np.random.seed(10)
temperatures_larges = np.random.uniform(15, 40, 24)
# Génération du masque de booléens pour les valeurs strictement supérieures à 35
anomalies = temperatures_larges > 35
# Somme du tableau de booléens pour compter les True
nombre_anomalies = np.sum(anomalies)

print("Nombre total de températures anormales :", nombre_anomalies)

Nombre total de températures anormales : 3
